import {
    MenuItem,
    Table,
    Order,
    InventoryItem,
    Staff,
    PurchaseOrder,
    MenuCategory,
    TableStatus,
    OrderStatus,
    StockStatus,
} from '@/types';
import { generateId } from './utils';

// Menu Items Mock Data
export const mockMenuItems: MenuItem[] = [
    // Coffee
    {
        id: '1',
        name: 'Espresso',
        description: 'Strong and bold Italian coffee',
        category: 'Coffee',
        price: 120,
        prepTime: 3,
        isAvailable: true,
        tags: ['Popular', 'Vegan'],
        image: '/menu/espresso.jpg',
    },
    {
        id: '2',
        name: 'Cappuccino',
        description: 'Espresso with steamed milk foam',
        category: 'Coffee',
        price: 150,
        prepTime: 5,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/cappuccino.jpg',
    },
    {
        id: '3',
        name: 'Latte',
        description: 'Smooth espresso with steamed milk',
        category: 'Coffee',
        price: 160,
        prepTime: 5,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/latte.jpg',
    },
    {
        id: '4',
        name: 'Americano',
        description: 'Espresso diluted with hot water',
        category: 'Coffee',
        price: 130,
        prepTime: 3,
        isAvailable: true,
        tags: ['Vegan'],
        image: '/menu/americano.jpg',
    },
    {
        id: '5',
        name: 'Mocha',
        description: 'Chocolate-flavored variant of latte',
        category: 'Coffee',
        price: 180,
        prepTime: 6,
        isAvailable: true,
        tags: [],
        image: '/menu/mocha.jpg',
    },
    {
        id: '6',
        name: 'Cold Brew',
        description: 'Smooth cold coffee brewed for 12 hours',
        category: 'Coffee',
        price: 170,
        prepTime: 2,
        isAvailable: true,
        tags: ['New', 'Popular'],
        image: '/menu/coldbrew.jpg',
    },
    {
        id: '7',
        name: 'Flat White',
        description: 'Velvety microfoam over espresso',
        category: 'Coffee',
        price: 165,
        prepTime: 5,
        isAvailable: true,
        tags: [],
        image: '/menu/flatwhite.jpg',
    },
    {
        id: '8',
        name: 'Affogato',
        description: 'Espresso poured over vanilla ice cream',
        category: 'Coffee',
        price: 190,
        prepTime: 4,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/affogato.jpg',
    },

    // Tea
    {
        id: '9',
        name: 'Masala Chai',
        description: 'Traditional Indian spiced tea',
        category: 'Tea',
        price: 80,
        prepTime: 5,
        isAvailable: true,
        tags: ['Popular', 'Spicy'],
        image: '/menu/masalachai.jpg',
    },
    {
        id: '10',
        name: 'Green Tea',
        description: 'Light and refreshing Japanese green tea',
        category: 'Tea',
        price: 90,
        prepTime: 4,
        isAvailable: true,
        tags: ['Vegan', 'Organic'],
        image: '/menu/greentea.jpg',
    },
    {
        id: '11',
        name: 'Earl Grey',
        description: 'Classic black tea with bergamot',
        category: 'Tea',
        price: 100,
        prepTime: 4,
        isAvailable: true,
        tags: ['Vegan'],
        image: '/menu/earlgrey.jpg',
    },
    {
        id: '12',
        name: 'Chamomile Tea',
        description: 'Calming herbal tea',
        category: 'Tea',
        price: 95,
        prepTime: 4,
        isAvailable: true,
        tags: ['Vegan', 'Organic'],
        image: '/menu/chamomile.jpg',
    },
    {
        id: '13',
        name: 'Iced Lemon Tea',
        description: 'Refreshing cold tea with lemon',
        category: 'Tea',
        price: 110,
        prepTime: 3,
        isAvailable: true,
        tags: ['Vegan', 'Popular'],
        image: '/menu/icedlemontea.jpg',
    },
    {
        id: '14',
        name: 'Matcha Latte',
        description: 'Japanese green tea latte',
        category: 'Tea',
        price: 180,
        prepTime: 5,
        isAvailable: true,
        tags: ['New', 'Popular'],
        image: '/menu/matchalatte.jpg',
    },

    // Bakery
    {
        id: '15',
        name: 'Croissant',
        description: 'Buttery French pastry',
        category: 'Bakery',
        price: 120,
        prepTime: 2,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/croissant.jpg',
    },
    {
        id: '16',
        name: 'Chocolate Muffin',
        description: 'Rich chocolate muffin',
        category: 'Bakery',
        price: 100,
        prepTime: 2,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/chocolatemuffin.jpg',
    },
    {
        id: '17',
        name: 'Blueberry Muffin',
        description: 'Fresh blueberry muffin',
        category: 'Bakery',
        price: 110,
        prepTime: 2,
        isAvailable: true,
        tags: [],
        image: '/menu/blueberrymuffin.jpg',
    },
    {
        id: '18',
        name: 'Cinnamon Roll',
        description: 'Sweet and sticky cinnamon roll',
        category: 'Bakery',
        price: 130,
        prepTime: 3,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/cinnamonroll.jpg',
    },
    {
        id: '19',
        name: 'Bagel with Cream Cheese',
        description: 'Toasted bagel with cream cheese',
        category: 'Bakery',
        price: 140,
        prepTime: 4,
        isAvailable: true,
        tags: [],
        image: '/menu/bagel.jpg',
    },
    {
        id: '20',
        name: 'Danish Pastry',
        description: 'Flaky pastry with fruit filling',
        category: 'Bakery',
        price: 125,
        prepTime: 2,
        isAvailable: true,
        tags: [],
        image: '/menu/danish.jpg',
    },
    {
        id: '21',
        name: 'Brownie',
        description: 'Fudgy chocolate brownie',
        category: 'Bakery',
        price: 95,
        prepTime: 2,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/brownie.jpg',
    },
    {
        id: '22',
        name: 'Cheesecake Slice',
        description: 'Creamy New York style cheesecake',
        category: 'Bakery',
        price: 180,
        prepTime: 2,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/cheesecake.jpg',
    },

    // Sandwiches
    {
        id: '23',
        name: 'Club Sandwich',
        description: 'Triple-decker with chicken, bacon, lettuce, tomato',
        category: 'Sandwiches',
        price: 220,
        prepTime: 8,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/clubsandwich.jpg',
    },
    {
        id: '24',
        name: 'Grilled Cheese',
        description: 'Classic grilled cheese sandwich',
        category: 'Sandwiches',
        price: 150,
        prepTime: 6,
        isAvailable: true,
        tags: ['Veg'],
        image: '/menu/grilledcheese.jpg',
    },
    {
        id: '25',
        name: 'Veggie Wrap',
        description: 'Fresh vegetables in a tortilla wrap',
        category: 'Sandwiches',
        price: 180,
        prepTime: 7,
        isAvailable: true,
        tags: ['Veg', 'Vegan'],
        image: '/menu/veggiewrap.jpg',
    },
    {
        id: '26',
        name: 'Chicken Panini',
        description: 'Grilled chicken panini with pesto',
        category: 'Sandwiches',
        price: 210,
        prepTime: 9,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/chickenpanini.jpg',
    },
    {
        id: '27',
        name: 'BLT Sandwich',
        description: 'Bacon, lettuce, and tomato sandwich',
        category: 'Sandwiches',
        price: 190,
        prepTime: 7,
        isAvailable: true,
        tags: [],
        image: '/menu/blt.jpg',
    },
    {
        id: '28',
        name: 'Tuna Melt',
        description: 'Tuna salad with melted cheese',
        category: 'Sandwiches',
        price: 200,
        prepTime: 8,
        isAvailable: true,
        tags: [],
        image: '/menu/tunamelt.jpg',
    },

    // Specials
    {
        id: '29',
        name: 'Avocado Toast',
        description: 'Smashed avocado on sourdough with poached egg',
        category: 'Specials',
        price: 240,
        prepTime: 10,
        isAvailable: true,
        tags: ['Popular', 'New'],
        image: '/menu/avocadotoast.jpg',
    },
    {
        id: '30',
        name: 'Acai Bowl',
        description: 'Acai smoothie bowl with granola and fruits',
        category: 'Specials',
        price: 260,
        prepTime: 8,
        isAvailable: true,
        tags: ['Vegan', 'Popular', 'Organic'],
        image: '/menu/acaibowl.jpg',
    },
    {
        id: '31',
        name: 'Pancake Stack',
        description: 'Fluffy pancakes with maple syrup and butter',
        category: 'Specials',
        price: 220,
        prepTime: 12,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/pancakes.jpg',
    },
    {
        id: '32',
        name: 'French Toast',
        description: 'Classic French toast with berries',
        category: 'Specials',
        price: 210,
        prepTime: 10,
        isAvailable: true,
        tags: [],
        image: '/menu/frenchtoast.jpg',
    },
    {
        id: '33',
        name: 'Smoothie Bowl',
        description: 'Mixed berry smoothie bowl with toppings',
        category: 'Specials',
        price: 230,
        prepTime: 7,
        isAvailable: true,
        tags: ['Vegan', 'Organic'],
        image: '/menu/smoothiebowl.jpg',
    },
    {
        id: '34',
        name: 'Eggs Benedict',
        description: 'Poached eggs with hollandaise on English muffin',
        category: 'Specials',
        price: 250,
        prepTime: 12,
        isAvailable: true,
        tags: ['Popular'],
        image: '/menu/eggsbenedict.jpg',
    },
];

// Tables Mock Data
export const mockTables: Table[] = Array.from({ length: 15 }, (_, i) => {
    const number = i + 1;
    const capacities = [2, 4, 6, 8];
    const statuses: TableStatus[] = ['free', 'occupied', 'reserved', 'billing'];

    return {
        id: `table-${number}`,
        number,
        capacity: capacities[Math.floor(Math.random() * capacities.length)],
        status: i < 3 ? 'occupied' : i < 5 ? 'billing' : i < 7 ? 'reserved' : 'free',
        currentOrderId: i < 3 ? `order-${i + 1}` : undefined,
    };
});

// Orders Mock Data
export const mockOrders: Order[] = [
    {
        id: 'order-1',
        tableId: 'table-1',
        items: [
            {
                id: 'oi-1',
                menuItem: mockMenuItems[1], // Cappuccino
                quantity: 2,
                notes: 'Extra hot',
                subtotal: 300,
            },
            {
                id: 'oi-2',
                menuItem: mockMenuItems[14], // Croissant
                quantity: 2,
                subtotal: 240,
            },
        ],
        status: 'in-progress',
        subtotal: 540,
        tax: 27,
        discount: 0,
        total: 567,
        createdAt: new Date(Date.now() - 15 * 60 * 1000), // 15 minutes ago
        updatedAt: new Date(Date.now() - 5 * 60 * 1000),
    },
    {
        id: 'order-2',
        tableId: 'table-2',
        items: [
            {
                id: 'oi-3',
                menuItem: mockMenuItems[28], // Avocado Toast
                quantity: 1,
                subtotal: 240,
            },
            {
                id: 'oi-4',
                menuItem: mockMenuItems[9], // Green Tea
                quantity: 1,
                subtotal: 90,
            },
        ],
        status: 'queued',
        subtotal: 330,
        tax: 16.5,
        discount: 0,
        total: 346.5,
        createdAt: new Date(Date.now() - 5 * 60 * 1000), // 5 minutes ago
        updatedAt: new Date(Date.now() - 5 * 60 * 1000),
    },
    {
        id: 'order-3',
        tableId: 'table-3',
        items: [
            {
                id: 'oi-5',
                menuItem: mockMenuItems[22], // Club Sandwich
                quantity: 1,
                subtotal: 220,
            },
            {
                id: 'oi-6',
                menuItem: mockMenuItems[5], // Cold Brew
                quantity: 1,
                subtotal: 170,
            },
            {
                id: 'oi-7',
                menuItem: mockMenuItems[20], // Brownie
                quantity: 1,
                subtotal: 95,
            },
        ],
        status: 'ready',
        subtotal: 485,
        tax: 24.25,
        discount: 0,
        total: 509.25,
        createdAt: new Date(Date.now() - 20 * 60 * 1000), // 20 minutes ago
        updatedAt: new Date(Date.now() - 2 * 60 * 1000),
    },
];

// Inventory Mock Data
export const mockInventory: InventoryItem[] = [
    {
        id: 'inv-1',
        name: 'Coffee Beans (Arabica)',
        currentStock: 25,
        unit: 'kg',
        reorderLevel: 10,
        supplier: 'Premium Coffee Co.',
        status: 'ok',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-2',
        name: 'Milk',
        currentStock: 40,
        unit: 'L',
        reorderLevel: 30,
        supplier: 'Fresh Dairy Farm',
        status: 'ok',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-3',
        name: 'Sugar',
        currentStock: 8,
        unit: 'kg',
        reorderLevel: 15,
        supplier: 'Sweet Supplies Inc.',
        status: 'critical',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-4',
        name: 'Flour',
        currentStock: 12,
        unit: 'kg',
        reorderLevel: 10,
        supplier: 'Baker\'s Choice',
        status: 'low',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-5',
        name: 'Eggs',
        currentStock: 15,
        unit: 'dozen',
        reorderLevel: 10,
        supplier: 'Farm Fresh Eggs',
        status: 'ok',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-6',
        name: 'Butter',
        currentStock: 5,
        unit: 'kg',
        reorderLevel: 8,
        supplier: 'Dairy Delights',
        status: 'critical',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-7',
        name: 'Chocolate Chips',
        currentStock: 6,
        unit: 'kg',
        reorderLevel: 5,
        supplier: 'Choco World',
        status: 'ok',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-8',
        name: 'Tea Leaves (Assorted)',
        currentStock: 8,
        unit: 'kg',
        reorderLevel: 6,
        supplier: 'Tea Garden Imports',
        status: 'ok',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-9',
        name: 'Bread Loaves',
        currentStock: 20,
        unit: 'pcs',
        reorderLevel: 15,
        supplier: 'Artisan Bakery',
        status: 'ok',
        lastUpdated: new Date(),
    },
    {
        id: 'inv-10',
        name: 'Cheese (Cheddar)',
        currentStock: 3,
        unit: 'kg',
        reorderLevel: 5,
        supplier: 'Cheese Masters',
        status: 'critical',
        lastUpdated: new Date(),
    },
];

// Staff Mock Data
export const mockStaff: Staff[] = [
    {
        id: 'staff-1',
        name: 'John Manager',
        role: 'manager',
        email: 'manager@cafe.com',
        phone: '+91 98765 43210',
        shift: 'morning',
        isActive: true,
        hireDate: new Date('2023-01-15'),
    },
    {
        id: 'staff-2',
        name: 'Sarah Cashier',
        role: 'cashier',
        email: 'cashier@cafe.com',
        phone: '+91 98765 43211',
        shift: 'afternoon',
        isActive: true,
        hireDate: new Date('2023-03-20'),
    },
    {
        id: 'staff-3',
        name: 'Mike Staff',
        role: 'staff',
        email: 'staff@cafe.com',
        phone: '+91 98765 43212',
        shift: 'evening',
        isActive: true,
        hireDate: new Date('2023-05-10'),
    },
    {
        id: 'staff-4',
        name: 'Emma Barista',
        role: 'staff',
        email: 'emma@cafe.com',
        phone: '+91 98765 43213',
        shift: 'morning',
        isActive: true,
        hireDate: new Date('2023-06-01'),
    },
    {
        id: 'staff-5',
        name: 'David Cook',
        role: 'staff',
        email: 'david@cafe.com',
        phone: '+91 98765 43214',
        shift: 'afternoon',
        isActive: true,
        hireDate: new Date('2023-07-15'),
    },
    {
        id: 'staff-6',
        name: 'Lisa Waiter',
        role: 'cashier',
        email: 'lisa@cafe.com',
        phone: '+91 98765 43215',
        shift: 'evening',
        isActive: true,
        hireDate: new Date('2023-08-20'),
    },
    {
        id: 'staff-7',
        name: 'Tom Server',
        role: 'staff',
        email: 'tom@cafe.com',
        phone: '+91 98765 43216',
        shift: 'morning',
        isActive: false,
        hireDate: new Date('2023-02-10'),
    },
];

// Purchase Orders Mock Data
export const mockPurchaseOrders: PurchaseOrder[] = [
    {
        id: 'po-1',
        supplier: 'Premium Coffee Co.',
        items: [
            {
                itemId: 'inv-1',
                itemName: 'Coffee Beans (Arabica)',
                quantity: 20,
                unit: 'kg',
                pricePerUnit: 800,
            },
        ],
        totalAmount: 16000,
        status: 'delivered',
        orderDate: new Date('2025-12-10'),
        deliveryDate: new Date('2025-12-12'),
    },
    {
        id: 'po-2',
        supplier: 'Sweet Supplies Inc.',
        items: [
            {
                itemId: 'inv-3',
                itemName: 'Sugar',
                quantity: 25,
                unit: 'kg',
                pricePerUnit: 50,
            },
        ],
        totalAmount: 1250,
        status: 'ordered',
        orderDate: new Date('2025-12-15'),
    },
    {
        id: 'po-3',
        supplier: 'Dairy Delights',
        items: [
            {
                itemId: 'inv-6',
                itemName: 'Butter',
                quantity: 10,
                unit: 'kg',
                pricePerUnit: 450,
            },
            {
                itemId: 'inv-10',
                itemName: 'Cheese (Cheddar)',
                quantity: 8,
                unit: 'kg',
                pricePerUnit: 600,
            },
        ],
        totalAmount: 9300,
        status: 'pending',
        orderDate: new Date('2025-12-16'),
    },
];
